### ISSUE TITLE
Add initial build info

### ISSUE THREAD

**Issue by tobigithub** [kusterlab/prosit#3]
Hi,
some additional info could be added to the readme for initial setup of prosit,
it basically helps people that are not that familiar with make and docker.
Also make build did not work, probably has to elevate with sudo.

````
sudo make build
````
which results in:
````
nvidia-docker build -qf Dockerfile -t prosit .
sha256:d224c2ac898b32662b6265ae7a37dd1872dd98defe4cf86c6fd3acbe7f006c2e
prosit@champagne:~/prosit$

**Comment by gessulat** [comment]
The output looks good I think. You can try `make jump` and see if you get an interactive shell within the built container.

**Comment by gessulat** [comment]
Will add detailed build information!

**Comment by tony-jy-zhao** [comment]
Very useful. A more detailed guide in README should help people get started easily.

**Comment by gessulat** [comment]
Please refer to: https://github.com/kusterlab/prosit#installation
The required software and its versions are stated as tested.

**Comment by MarcIsak** [comment]
Hi, I have not managed to run prosit on my computer, but I guess I am quite close. 

I am running bash on Windows 10 (I use the Windows subsystem for Linux - Ubuntu Distribution). I can access the prosit folder (which should contain all files plus installed files, see attached image). Unfortunately, it seems like prosit cannot find the nvidia-docker when I try to use the make server command(see error message in the attached bash screen dump
<img width="562" alt="nvidia_docker_not_found2" src="https://user-images.githubusercontent.com/47174270/60526431-a375c800-9cf0-11e9-9896-43a3802d2230.png">
<img width="490" alt="nvidia_docker_not_found" src="https://user-images.githubusercontent.com/47174270/60526434-a40e5e80-9cf0-11e9-85b3-4c37cbc9b106.png">

). 

I am not sure if this is because I did not configure the dependencies properly). I have downloaded docker, nvidia-docker and make as specified, but I did it before installing prosit..

Any tips to a computer rookie?

**Comment by gessulat** [comment]
I would assume that the error is caused by one of the following:

1. nvdia-docker is not installed
2. nvidia-docker is not in your path

To ensure that nvidia-docker is setup in a way so that Prosit's makefile can make use of it you can run 
```
 nvidia-docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
```
Which should show you the current utilization of you GPU(s).

https://github.com/NVIDIA/nvidia-docker recommends 
```
docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
``` 
which is basically the same.

**Comment by gessulat** [comment]
The order in which you downloaded Prosit and it's dependencies does not matter. Except for nvidia-docker that needs to be installed after docker.

**Comment by tobigithub** [comment]
@MarcIsak @gessulat 

Nvidia-docker is not supported under WINDOWS. Reason, it would require a pass-through of all the GPU functionality. See https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported

> 
> Is Microsoft Windows supported?
> No, we do not support Microsoft Windows (regardless of the version), however you can use the native Microsoft Windows Docker client to deploy your containers remotely (refer to the dockerd documentation).
> 
> Do you support Microsoft native container technologies (e.g. Windows server, Hyper-v)?
> No, we do not support native Microsoft container technologies.


So I see multiple solutions. 

1. Use the native "jump" code example to run prosit predictions and training under Windows. Basically remove the server functionality and just run a python training and prediction set under Windows using TensorFlow GPU, Keras, pandas and all other prediction packages.

2. Use dual-boot on a Windows machine, allowing a LINUX partition to be selected upon boot.

3. Use  Amazon or Google cloud to run prosit

4. Use the web-service from the Kusterlab

5. Ask a Linux guy if they can install the prosit software

6. Get a "cheap" LINUX box with a GTX 1050 (they are around 600 dollars)

**Comment by MarcIsak** [comment]
@tobigithub @gessulat 

Hi,

yes, I realized that it would not work to install nvidia-docker on Windows. So instead I downloaded Ubuntu and ran it through Windows 10's WSL feature. Problem was that I couldn't install Docker properly as I got this message in the end when I wanted to see that everything worked out: 
 _System has not been booted with systemd as init system (PID 1). Can't operate._

To address the above points. 

1. Sounds interesting, but I have no clue how to set up this workaround and would need some help. 
2. This is a viable option, that perhaps could help me get past the problem with installing Docker on the WSL Ubuntu. 
3. No idea how to do this. Would need some help.
4. Maybe the last resort. Waiting times for result output is the problem here, and the limited number of RAW-file that can be uploaded. 
5. Very likely 
6. I think point 2 is a better option. 

Thanks for your input! I won´t keep spamming about this so the thread is definitely closed here :).

**Comment by tobigithub** [comment]
@MarcIsak 
actually the docker file is available, so under Windows 
you can just run the pip installer or use a conda environment.

Then you modify the code without the docker "frame".
So usage under Windows should not be a problem.

````
FROM tensorflow/tensorflow:1.10.1-gpu-py3
RUN pip install keras==2.2.1 h5py tables flask pyteomics lxml

ENV KERAS_BACKEND=tensorflow
ENV TF_CPP_MIN_LOG_LEVEL=3
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ADD prosit/ /root/prosit
RUN cd /root/
WORKDIR /root/
````
