### ISSUE TITLE
Please make sure that your uploaded "msms.txt" is also named "msms.txt"

### ISSUE THREAD

**Issue by yangkl96** [kusterlab/prosit#82]
Hello,

I submitted an msms.txt for CE calibration and received the above error for task 32B7C77BC3289AFD8C193081E9D2795C. I made sure the file had that name. Do you know what the error might be caused by? The msms.txt contains some PSMs from other raw files (I searched multiple raw files together but could only submit one to CE calibration), but I have done this before with no error

Thanks,
Kevin

**Comment by jamc1996** [comment]
Hi,

I'm having the same issue on the rescoring pipeline with the same error message. My msms.txt was definitely only searched from one raw file.

Thanks,
John.

**Comment by WassimG** [comment]
Can you please add your task ID will check both tasks and let you know what is the issue.

**Comment by yangkl96** [comment]
I had two tasks with the same error:
7F1FA0DB0D03CBF1B9451A8EC94283FB
5B9619C6113CF8DEC809F82898468302

**Comment by jamc1996** [comment]
My Task ID was: 9BB2212CEBE769F01DC0543133B15DC8

**Comment by WassimG** [comment]
I have checked both tasks for both the issue is that we assume for Cysteine that Carbamidomethylation is a fixed modification. For yangkl96 in the msms there was (Cysteinyl) after Cysteine amino acid in the peptide sequence not sure what this means for MQ output but we couldn't handle this. For jamc1996 there was (ca) after Cysteines I believe this is Carbamidomethylation and since we handle Carbamidomethylation as a fixed modification we assume that the C in the peptide sequence wouldn't have a modification in it.

**Comment by jamc1996** [comment]
That's great, thank you for your help!
