### ISSUE TITLE
"Can't get the response from the server"

### ISSUE THREAD

**Issue by phil812** [kusterlab/prosit#90]
Dear developers,

I used your program now many times successfully and until approx. one week ago, I always could either download the finished results or see an error message. Recently when I want to download results after a supposed finished search, I can click on the download button and after some seconds, I will get the following message:

"Error: HttpClient.getResponse: Can't get the response from the server: IPCon error: \"Connection to 131.159.152.7 lost while reading response.\""
An example would be Task-ID: A85D90F678A25047D624BAD58FD335E9

Thank you very much in advance

Best wishes,
Philip

**Comment by LLautenbacher** [comment]
Hi Phillip,


this error happens because the file you uploaded is too large. Split your file across multiple jobs such that each job has no more than 800k entries.


Best,

Ludwig


-----------------------------------------------
Ludwig Lautenbacher
Doctoral Candidate
Computational Mass Spectrometry
TUM School of Life Sciences
Technical University of Munich
Maximus-von-Imhof-Forum 3
D - 85354 Freising
Germany
Phone: +49 8161 71 2146
________________________________
From: phil812 ***@***.***>
Sent: Tuesday, October 25, 2022 1:46:19 PM
To: kusterlab/prosit
Cc: Subscribed
Subject: [kusterlab/prosit] "Can't get the response from the server" (Issue #90)


Dear developers,

I used your program now many times successfully and until approx. one week ago, I always could either download the finished results or see an error message. Recently when I want to download results after a supposed finished search, I can click on the download button and after some seconds, I will get the following message:

"Error: HttpClient.getResponse: Can't get the response from the server: IPCon error: "Connection to 131.159.152.7 lost while reading response.""
An example would be Task-ID: A85D90F678A25047D624BAD58FD335E9

Thank you very much in advance

Best wishes,
Philip
